services:
  - name: realdoc-api
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port ${PORT}
envVars:
  - key: MONGODB_URI
    fromGroup: mongodb
  - key: PORT
    value: 8000
  - key: JWT_SECRET
    generateValue: true
  - key: JWT_ALGORITHM
    value: HS256
  - key: ACCESS_TOKEN_EXPIRE_MINUTES
    value: 30
  - key: FRONTEND_URL
    value: https://realdoc-app.onrender.com
